apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  fake-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: "application/fake-ingress"
    repoURL: https://github.com/tiagat/poc-ingress-solutions
    targetRevision: main
    directory:
      jsonnet:
        extVars:
          - name: ingressCount
            value: "10"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
