apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    name: in-cluster
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.9.0
    helm:
      parameters:
        - name: controller.customConfigMap
          value: nginx-config
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
